@startuml
set namespaceSeparator ::

class "builder_shop::builder_pizza.dart::PizzaBuilder" {
  -String _crust
  -int _diameter
  -Set<String> _toppings
  +String crust
  +int diameter
  +Set<String> toppings
  -void _ensureCheese()
  +Pizza build()
}

class "builder_shop::builder_pizza.dart::Pizza" {
  -String _crust
  -int _diameter
  -Set<String> _toppings
  +String crust
  +int diameter
  +String toppings
  -String _stringifiedToppings()
  +String toString()
}


@enduml